name: "embeddings"
hyper_parameters:
  lr: 0.001
  bs: 64
  mom: 0.9
  wd: 0.0001
  ep: 100
directories:
  train_data: "data/few_shapes/"
  train_labels: "data/captions.tablechair.csv"
  vocabulary: "data/full_voc.csv"
  text_model_load: "output/"
  shape_model_load: "output/"
  model_save: "results/"
  tensorboard: "tensorboard/"