name: "embeddings"
hyper_parameters:
  lr: 0.001
  bs: 64
  mom: 0.9
  wd: 0.0001
  ep: 100
  oversample: 3
metric: ["s2t", "t2s"]      # evaluation metrices
nns: 20                     # numer of nearest neighbors for evaluation metric
directories:
  train_data: "data/nrrd_256_filter_div_32_solid/"
  train_labels: "data/full_preprocessed.captions.csv"
  vocabulary: "data/full_voc.csv"
  text_model_load: "output/"
  shape_model_load: "output/"
  model_save: "results/"
  tensorboard: "tensorboard/"
