name: "embeddings"
hyper_parameters:
  lr: 0.001
  bs: 4
  mom: 0.9
  wd: 0.0001
  ep: 100
  oversample: 3
loss: "ratio"                       # margin or ratio
generate_condition: "cross_modal"   # cross_modal or uni_modal
generate_batch: "random"           # use random or smart batch
triplet: ["s2t", "t2s"]           # what kind of triplet should be used for training/evaluation
metric: ["s2t", "t2s"]            # evaluation metrices
nns: 20                           # numer of nearest neighbors for evaluation metric
dataset: "primitives"             # primitives or shapenet
categorize: "shape"               # shape or shape_color
directories:
  train_data: "data/nrrd_256_filter_div_32_solid/"
  train_labels: "data/full_preprocessed.captions.csv"
  primitives: "data/test_primitives/"
  vocabulary: "data/primitives_voc.csv"
  text_model_load: "output/"
  shape_model_load: "output/"
  model_save: "results/test/"
  tensorboard: "tensorboard/"
