name: "tsne"
version: ["t2t", "s2t"]
hyper_parameters:
  n: 100  # n number of random data to plot
dataset: "primitives"       # primitives or shapenet
categorize: "shape"         # shape or shape_color
directories:
  train_data: "data/nrrd_256_filter_div_32_solid/" 
  train_labels: "data/full_preprocessed.captions.csv"
  primitives: "data/test_primitives/"
  vocabulary: "data/primitives_voc.csv"
  text_model_load: "results/test/text_encoder.pt"
  shape_model_load: "results/test/shape_encoder.pt"
  output: "tsne/"
