name: "test-config"
hyper_parameters:
  lr: 0.001
  bs: 64
  mom: 0.9
  wd: 0.0001
  ep: 0
triplet: ["s2t", "t2s"]
metric: ["s2t", "t2s"]
nns: 20
directories:
  train_data: "test/test_shapes/"
  train_labels: "test/test_captions.csv"
  vocabulary: "test/test_voc.csv"
  text_model_load: "output/"
  shape_model_load: "output/"
  model_save: "results/"
  tensorboard: "tensorboard/"