name: "retrieval"
version: ["s2t"]
hyper_parameters:
  k: 8  # k nearest neighbor
  n: 3  # n number of random data of which to find nearest neighbor
  bs: 1 # to receive a random triplet
directories:
  train_data: "data/nrrd_256_filter_div_32_solid/"
  train_labels: "data/full_preprocessed.captions.csv"
  vocabulary: "data/full_voc.csv"
  text_model_load: "local_results/01_loss_0.2416/text_encoder.pt"
  shape_model_load: "local_results/01_loss_0.2416/shape_encoder.pt"
  output: "local_results/test/"
