name: "retrieval"
version: ["t2s", "s2t"]
hyper_parameters:
  k: 8  # k nearest neighbor
  n: 3  # n number of random data of which to find nearest neighbor
  bs: 1 # to receive a random triplet
dataset: "shapenet"       # primitives or shapenet
categorize: "shape"         # shape or shape_color
directories:
  train_data: "data/nrrd_256_filter_div_32_solid/"
  train_labels: "data/full_preprocessed.captions.csv"
  primitives: "data/test_primitives/"
  vocabulary: "data/full_voc.csv"
  text_model_load: "local_results/presentation/cross_mixed/text_encoder.pt"
  shape_model_load: "local_results/presentation/cross_mixed/shape_encoder.pt"
  output: "local_results/presentation/cross_mixed/"
